### ISSUE TITLE
Build failed: No repository found at http://exyte.com/sweet/updates

### ISSUE THREAD

**Issue by dodie** [exyte/sweet.eclipse#3]
Hi!

I am trying to build the project on linux, with the following command:

mvn clean verify -Psweet.package.java -Declipse.simultaneous.release.repository="http://download.eclipse.org/releases/mars/201510021000"

But I get the following error:

...
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'sweet' from location http://exyte.com/sweet/updates/: No repository found at http://exyte.com/sweet/updates. -> [Help 1]
...

Are there any alternative repositories?

Thank you in advance,
David

**Comment by ystrot** [comment]
Hi Dávid,

We're currently updating our server infrastructure, so unfortunately our
update sites will be unavailable for few days. Could you please wait a
little bit? I will let you know when the transfer will be finished.

BTW, Sweet Eclipse still doesn't completely support linux, not sure you
will be able to use it there :-(

## 

Best regards,
Yuri Strot

**Comment by dodie** [comment]
Hi ystrot!

Thank you for your quick reply! Of course, I'll wait for the repo to be back online and then try again.
I know that linux is currently not supported, but after watching your presentation on infoq (https://www.infoq.com/presentations/ui-eclipse-rcp), I'd gladly spend some time fiddling with it.

Thanks,
David

**Comment by ystrot** [comment]
Ok, will keep you updated!

## 

Best regards,
Yuri Strot

**Comment by nirodg** [comment]
So far it worked for me 
```maven
[INFO] ------------------------------------------------------------------------
[INFO] Building org.eclipse.epp-buildall 4.5.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ org.eclipse.epp-buildall ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:regex-property (regex-property) @ org.eclipse.epp-buildall ---
[INFO] No match to regex 'epp\.package\.(\d*)' found in 'org.eclipse.epp-buildall'. The initial value 'org.eclipse.epp-buildall' is left as-is...
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-versions) @ org.eclipse.epp-buildall ---
[INFO] 
[INFO] --- tycho-source-plugin:0.23.1:plugin-source (plugin-source) @ org.eclipse.epp-buildall ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.eclipse.epp.package.common.feature ............. SUCCESS [  2.993 s]
[INFO] com.exyte.sweet.package.java ....................... SUCCESS [  1.164 s]
[INFO] com.exyte.sweet.package.java.feature ............... SUCCESS [  0.556 s]
[INFO] epp.package.java ................................... SUCCESS [04:47 min]
[INFO] org.eclipse.epp-buildall ........................... SUCCESS [  0.021 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:00 min
[INFO] Finished at: 2017-02-05T20:09:50+01:00
[INFO] Final Memory: 107M/958M
[INFO] ------------------------------------------------------------------------

```

**Comment by dodie** [comment]
Thank you for letting me know that the repo works again! The build works for me as well.
